[build]
  publish = "dist"
  command = "npm run build"

[[redirects]]
  from = "/master/*"
  to = "/master/index.html"
  status = 200

[[redirects]]
  from = "/planner/*"
  to = "/planner/index.html"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
