import { Injectable, NotFoundException, BadRequestException } from '@nestjs/common';
import { PrismaService } from '../prisma/prisma.service';
import { SecurityService } from './services/security.service';
import { FraudService } from './services/fraud.service';

@Injectable()
export class PaymentsService {
  constructor(
    private readonly prisma: PrismaService,
    private readonly securityService: SecurityService,
    private readonly fraudService: FraudService,
  ) {}

  async createOrder(bookingId: string, ipAddress?: string, deviceFingerprint?: string) {
    const booking = await this.prisma.booking.findUnique({
      where: { id: bookingId },
      include: {
        package: {
          include: {
            planner: {
              include: {
                paymentAccount: true,
                profile: true
              }
            }
          }
        }
      }
    });

    if (!booking) {
      throw new NotFoundException('Booking not found');
    }

    const plannerUser = booking.package.planner;
    const paymentAccount = plannerUser.paymentAccount;

    if (!paymentAccount || paymentAccount.activationStatus !== 'ACTIVE') {
      throw new BadRequestException('This planner cannot accept online payments yet. PhonePe account is not active.');
    }

    // Generate unique booking code if not set (PhonePe merchantOrderId)
    let bookingCode = booking.bookingCode;
    if (!bookingCode) {
      const prefix = 'BKN';
      const randomSuffix = Math.floor(100000 + Math.random() * 900000);
      bookingCode = `${prefix}-${randomSuffix}`;
    }

    // Set 30 minute expiry
    const expiresAt = new Date(Date.now() + 30 * 60 * 1000);

    // Save PhonePe transaction details back to Booking
    const updatedBooking = await this.prisma.booking.update({
      where: { id: bookingId },
      data: {
        bookingCode,
        expiresAt,
        ipAddress,
        deviceFingerprint,
        status: 'AWAITING_PAYMENT',
      },
    });

    // Decrypt the merchant credentials
    const merchantId = paymentAccount.phonepeMerchantId;

    // Simulate calling PhonePe API to generate dynamic checkout details
    // We return a mock QR image and payment link targeted for B2C travellers.
    // In a production setup, this would be generated by requesting https://api.phonepe.com/apis/hermes/pg/v1/pay
    const mockPaymentLink = `https://mock.phonepe.com/pay/${merchantId}?orderId=${bookingCode}&amount=${booking.totalAmount}`;
    
    // Create a mock QR Code base64 data for the traveller to scan (contains order and amount details)
    const mockQrData = `upi://pay?pa=${plannerUser.profile?.upiOrPaypalId || 'planner@upi'}&pn=${encodeURIComponent(plannerUser.name || 'Planner')}&am=${booking.totalAmount}&tr=${bookingCode}&tn=Booking%20${bookingCode}`;

    // Ensure corresponding Payment doc exists in database
    await this.prisma.payment.upsert({
      where: { bookingId },
      create: {
        bookingId,
        amount: booking.totalAmount,
        currency: 'INR',
        status: 'PENDING',
      },
      update: {
        amount: booking.totalAmount,
        status: 'PENDING',
      }
    });

    // Write to audit log
    await this.prisma.auditLog.create({
      data: {
        entityType: 'Booking',
        entityId: bookingId,
        actorType: 'SYSTEM',
        action: 'PAYMENT_INITIATED',
        after: { bookingCode, status: 'AWAITING_PAYMENT', expiresAt }
      }
    });

    return {
      bookingId,
      bookingCode,
      grandTotal: booking.totalAmount,
      expiresAt,
      paymentLink: mockPaymentLink,
      qrData: mockQrData,
      merchantId,
    };
  }

  async handleWebhook(payload: any, authHeader: string) {
    // fast ack audit
    await this.prisma.auditLog.create({
      data: {
        entityType: 'Payment',
        entityId: payload?.payload?.merchantOrderId || 'unknown_id',
        actorType: 'WEBHOOK',
        action: 'WEBHOOK_RECEIVED',
        after: payload
      }
    });

    // Check basic auth signature
    const merchantId = payload?.payload?.merchantId;
    const paymentAccount = await this.prisma.plannerPaymentAccount.findFirst({
      where: { phonepeMerchantId: merchantId },
    });

    if (!paymentAccount) {
      console.warn(`Webhook failed: no planner account found with Merchant ID ${merchantId}`);
      return { success: false, reason: 'Invalid Merchant ID' };
    }

    const decryptedPassword = this.securityService.decrypt(paymentAccount.webhookAuthPasswordEncrypted);
    const authValid = this.securityService.verifyBasicAuth(authHeader, paymentAccount.webhookAuthUsername, decryptedPassword);

    if (!authValid) {
      await this.prisma.auditLog.create({
        data: {
          entityType: 'Payment',
          entityId: paymentAccount.id,
          actorType: 'WEBHOOK',
          action: 'WEBHOOK_AUTH_FAILED',
          after: { authHeader, merchantId }
        }
      });
      return { success: false, reason: 'Auth signature verification failed' };
    }

    if (payload.event !== 'checkout.order.completed') {
      return { success: true, reason: 'Ignored event type' };
    }

    const { merchantOrderId, amount, paymentDetails, state } = payload.payload;
    const transactionId = paymentDetails?.[0]?.transactionId || `TXN-${Date.now()}`;
    const amountInRs = amount / 100; // PhonePe details are in paise, convert to Rs

    // Check 2: Booking Exists
    const booking = await this.prisma.booking.findUnique({
      where: { bookingCode: merchantOrderId },
      include: { payment: true }
    });

    if (!booking) {
      console.error(`Orphan payment webhook: Booking code ${merchantOrderId} not found.`);
      return { success: false, reason: 'Orphan payment' };
    }

    // Check 3: Idempotency check
    if (booking.status === 'VERIFIED') {
      return { success: true, reason: 'Already verified' };
    }

    // Move status to VERIFYING temporarily
    await this.prisma.booking.update({
      where: { id: booking.id },
      data: { status: 'VERIFYING' }
    });

    const flags: string[] = [];
    const logsToCreate: any[] = [];

    const logCheck = (checkName: string, passed: boolean, detail: string) => {
      logsToCreate.push({
        bookingId: booking.id,
        checkName,
        passed,
        detail
      });
    };

    // Check 4: Duplicate transaction ID
    const duplicateTxn = await this.prisma.payment.findFirst({
      where: { transactionId },
    });
    logCheck('DUPLICATE_TXN', !duplicateTxn, duplicateTxn ? `Transaction ID already used by booking ${duplicateTxn.bookingId}` : 'unique');
    if (duplicateTxn) flags.push('DUPLICATE_TXN');

    // Check 5: Amount matches
    const amountMatches = amountInRs === booking.totalAmount;
    logCheck('AMOUNT_MATCH', amountMatches, `expected=${booking.totalAmount} got=${amountInRs}`);
    if (!amountMatches) flags.push('AMOUNT_MISMATCH');

    // Check 6: Within window
    const onTime = !booking.expiresAt || new Date() <= booking.expiresAt;
    logCheck('WITHIN_WINDOW', onTime, `expiresAt=${booking.expiresAt}`);
    if (!onTime) flags.push('LATE_PAYMENT');

    // Check 7: Planner Account Active
    const plannerActive = paymentAccount.activationStatus === 'ACTIVE';
    logCheck('PLANNER_ACTIVE', plannerActive, paymentAccount.activationStatus);
    if (!plannerActive) flags.push('PLANNER_INACTIVE');

    // Call Fraud Scoring Layer
    const { score, contributions } = await this.fraudService.computeFraudScore(booking.id, {
      amount: amountInRs,
      transactionId,
      flags,
    });

    // Write all verification logs to DB
    for (const logItem of logsToCreate) {
      await this.prisma.verificationLog.create({ data: logItem });
    }

    // Save fraud contributions
    for (const c of contributions) {
      await this.prisma.fraudFlag.create({
        data: {
          bookingId: booking.id,
          flagType: c.type,
          scoreContribution: c.points,
        }
      });
    }

    // Determine final status
    const verifiedStatus = flags.length === 0 && score < 50;
    const finalPaymentStatus = verifiedStatus ? 'VERIFIED' : 'FLAGGED';
    const finalBookingStatus = verifiedStatus ? 'VERIFIED' : 'MANUAL_REVIEW';

    // Update payment record
    await this.prisma.payment.update({
      where: { bookingId: booking.id },
      data: {
        transactionId,
        amountReceived: amountInRs,
        verificationSource: 'phonepe_webhook',
        status: finalPaymentStatus,
        fraudScore: score,
        fraudFlags: flags,
        rawWebhookPayload: payload
      }
    });

    // Update booking status
    const beforeStatus = booking.status;
    await this.prisma.booking.update({
      where: { id: booking.id },
      data: { status: finalBookingStatus }
    });

    // Log the transition
    await this.prisma.auditLog.create({
      data: {
        entityType: 'Booking',
        entityId: booking.id,
        actorType: 'WEBHOOK',
        action: 'STATE_TRANSITION',
        before: { status: beforeStatus },
        after: { status: finalBookingStatus }
      }
    });

    return {
      success: true,
      bookingId: booking.id,
      status: finalBookingStatus,
      fraudScore: score,
      flags,
    };
  }

  // Admin Manual review support
  async adminVerifyPayment(bookingId: string, adminId: string, action: 'APPROVE' | 'REJECT', reason: string) {
    const booking = await this.prisma.booking.findUnique({
      where: { id: bookingId },
    });

    if (!booking) {
      throw new NotFoundException('Booking not found');
    }

    const beforeStatus = booking.status;
    const finalStatus = action === 'APPROVE' ? 'VERIFIED' : 'REJECTED';
    const finalPaymentStatus = action === 'APPROVE' ? 'VERIFIED' : 'REJECTED';

    await this.prisma.booking.update({
      where: { id: bookingId },
      data: { status: finalStatus }
    });

    await this.prisma.payment.update({
      where: { bookingId },
      data: { status: finalPaymentStatus }
    });

    await this.prisma.adminAction.create({
      data: {
        adminId,
        bookingId,
        action,
        reason
      }
    });

    await this.prisma.auditLog.create({
      data: {
        entityType: 'Booking',
        entityId: bookingId,
        actorType: 'ADMIN',
        actorId: adminId,
        action: 'ADMIN_OVERRIDE',
        before: { status: beforeStatus },
        after: { status: finalStatus }
      }
    });

    return { bookingId, status: finalStatus };
  }
}
